# Generated by Django 4.2.2 on 2023-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_imagem_nome_alter_imagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagens',
            field=models.ManyToManyField(related_name='imagens', to='portfolio.imagem'),
        ),
    ]
