# Generated by Django 4.2.2 on 2023-07-04 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projeto_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTecnologia', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=500)),
                ('jaUsei', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='autor',
            name='areas',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='projetos'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='nome',
            field=models.TextField(default='sem nome', max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagens',
            field=models.ManyToManyField(related_name='projetos', to='portfolio.imagem'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AddField(
            model_name='educacao',
            name='imagens',
            field=models.ManyToManyField(related_name='educacao', to='portfolio.imagem'),
        ),
    ]
