# Generated by Django 4.2.2 on 2023-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_educacao_web_remove_autor_areas_alter_imagem_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('dataHora', models.DateTimeField(null=True)),
            ],
        ),
    ]
